spring:
  main:
    banner-mode: "off"
  application:
    name: my-streaming-app
server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 50
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

