apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kstream-app
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kstream-app
  template:
    metadata:
      labels:
        app: kstream-app
        monitored: "yes"
    spec:
      volumes:
        - name: state-dir
          hostPath:
            path: stream-state-store
      containers:
        - name: kstream-app
          image: samsoft:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: state-dir
              mountPath: stream-state-store
          resources:
            requests:
              memory: "1G"
              cpu: "120m"
            limits:
              memory: "1G"
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: kafka
  name: my-pmon
  labels:
    release: observe
spec:
  selector:
    matchLabels:
      monitored: "yes"
  podMetricsEndpoints:
    - port: web
      scheme: http
      path: /actuator/prometheus
      interval: 2s
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  namespace: kafka
  name: payments
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5
  replicas: 1
  config:
    retention.days: 2
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  namespace: kafka
  name: orders
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5
  replicas: 1
  config:
    retention.days: 2
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  namespace: kafka
  name: failed-order
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5
  replicas: 1
  config:
    retention.days: 2
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  namespace: kafka
  name: success-order
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5
  replicas: 1
  config:
    retention.days: 2
    segment.bytes: 1073741824
