apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-app
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming-app
  template:
    metadata:
      labels:
        app: streaming-app
        monitored: "yes"
    spec:
      containers:
        - name: streaming-app
          image: samsoft:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "400Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: web
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: kafka
  name: my-pmon
  labels:
    team: frontend
    release: observe
spec:
  selector:
    matchLabels:
      monitored: "yes"
  podMetricsEndpoints:
    - port: web
      scheme: http
      path: /actuator/prometheus
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  namespace: kafka
  name: payments
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  namespace: kafka
  name: orders
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824